theme = "hyde"
baseURL = "http://briangrichards.com"
languageCode = "en-us"
title = "Brian G. Richards"

[params] 
  description = "Data Scientist, Physics Ph.D., and R Enthusiast"

[[menu.main]]
  name = "About" 
  url = "/about/" 
  weight = 2
  
[[menu.main]]
  name = "CV and Resume"
  url = "/cv/"
  weight = 3