theme = "hyde"
baseURL = "http://briangrichards.com"
languageCode = "en-us"
title = "Brian G. Richards"

[params] 
  description = "Data Scientist and Physics Ph.D."

[[menu.main]]
  name = "About" 
  url = "/About/" 
  weight = 2