theme = "hyde"
baseURL = "http://briangrichards.com/"
languageCode = "en-us"
title = "Brian G. Richards"
relativeurls = true
googleAnalytics = "UA-106427662-1"

[params] 
  description = "Data Scientist, Physics Ph.D., and R Enthusiast"

[[menu.main]]
  name = "About" 
  url = "/about/" 
  weight = 2
  
[[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 3
  
[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/briangrichards/"
  weight = 4
  
[[menu.main]] 
  name = "GitHub"
  url = "https://github.com/bgrich"
  weight = 5
  