---
title: About
---

I am a Ph.D. candidate in the Ultrafast Laser and Atomic Physics Lab of Dr.
Bob Jones.

### Research Background

My current work is a study of dipole-dipole mediated resonant energy transfer
(RET) and the various ways that RET can be used to study cold atomic systems. I
study cold Rubidium Rydberg atoms in a magneto-optical trap (MOT). RET can be
used to exchange energy over long ranges between atoms trapped in a MOT. These
long range interactions allow the transfer of population from some starting
pair of Rydberg states to another final pair of Rydberg states. These long
range RET systems may also allow us to control the separation of the atoms
within the MOT and give us access to methods to control atom motion.

### Interests

My primary research interests include the development of open-access data
acquisition, processing, storage, and analysis pipelines for physics research.
I am currently developing a package for [R](https://www.r-project.org) called
[starkr](https://www.github.com/bgrich/starkr) that is currently available on
GitHub. This package provides functions to calculate the Stark map of
Rubidium-85 along with functions to calculate the quantum defect, radial matrix
element, and other useful functions. I plan to continue the development of this
package to improve the speed of the calculations along with expanding it to
cover more cases and possibly more atoms.

I am also interested in science communication, both amongst experts in
scientific fields and between experts and non-experts.
